@startuml Basic Sample
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
title
 <u>Context diagram</u> TO BE for Smart Home Application in common
end title

Person(user, "Клиент")



Boundary(sm, "Smart Home") {
    Person(impl, "Внедренец")
    Person(manager, "Менеджер") 
    Person(dev, "Член команды разработки")
    Person(accountant, "Бухгалтер") 
    Person(clvl, "Управляющий, ЛПР, Выгодоприобретатель")

    System_Boundary(sm_bound, "Smart home Application") {
        System(main_app, "SmartHome ", "Основное приложение", "", "React, C#, PostgreSQL")
    }
    System_Ext(sensor, "Датчик, совместимый с приложением")
    System_Ext(actuator, "Актуатор, совместимый с приложением")
}


'##########
'  МЕНЕДЖЕР  
'##########
Rel(manager, main_app, "<<Uses>>", "")

Rel(manager, clvl, "Предоставляет отчеты приложения о работе бизнеса")
Rel(manager, accountant, "Предоставляет отчеты приложения о работе бизнеса")


'##########
'  БУХГАЛТЕР, C-Level  
'##########
Rel(clvl, manager, "Управляет")
Rel(clvl, impl, "Управляет")
Rel(clvl, dev, "Управляет")


@enduml